import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Miss",
      email: "shawnastaff@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Space Kadet Shop",
        logo: "/images/skglobal.jpg",
        description: "Best-Seller",
        rating: 5,
        numReviews: 87,
      },
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Space Kadet Tee Shirt",
      category: "Men's Shirts",
      image: "/images/mensblacktee.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 15,
      rating: 4.5,
      numReviews: 10,
      description: "Black Space Kadet Tee Shirt",
    },
    {
      name: "Magic Baby Tee",
      category: "Women's Tops",
      image: "/images/magicbabytee.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 16,
      rating: 4.0,
      numReviews: 10,
      description: "Space Kadet Magic Women's Baby Tee",
    },
    {
      name: "SK Tank Top",
      category: "Women's Tops",
      image: "/images/sktank.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 29,
      rating: 4.8,
      numReviews: 17,
      description: "Space Kadet SK Tank Top",
    },
    {
      name: "Spacey Leggings",
      category: "Leggings",
      image: "/images/whitespacelyleggings.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 0,
      rating: 4.5,
      numReviews: 14,
      description: "Space Kadet Spacey Leggings",
    },
    {
      name: "SK Leggings",
      category: "Leggings",
      image: "/images/whitespacelyleggingssideview.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 12,
      rating: 4.5,
      numReviews: 10,
      description: "Space Kadet SK Leggings",
    },
  ],
};
export default data;
