const data = {
  products: [
    {
      _id: "1",
      name: "Space Kadet Tee Shirt",
      category: "Men's Shirts",
      image: "../images/mensblacktee.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 15,
      rating: 4.5,
      numReviews: 10,
      description: "Black Space Kadet Tee Shirt",
    },
    {
      _id: "2",
      name: "Magic Baby Tee",
      category: "Women's Tops",
      image: "../images/magicbabytee.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 16,
      rating: 4.0,
      numReviews: 10,
      description: "Space Kadet Magic Women's Baby Tee",
    },
    {
      _id: "3",
      name: "SK Tank Top",
      category: "Women's Tops",
      image: "../images/sktank.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 29,
      rating: 4.8,
      numReviews: 17,
      description: "Space Kadet SK Tank Top",
    },
    {
      _id: "4",
      name: "Spacey Leggings",
      category: "Leggings",
      image: "../images/whitespacelyleggings.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 0,
      rating: 4.5,
      numReviews: 14,
      description: "Space Kadet Spacey Leggings",
    },
    {
      _id: "5",
      name: "SK Leggings",
      category: "Leggings",
      image: "../images/whitespacelyleggingssideview.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 12,
      rating: 4.5,
      numReviews: 10,
      description: "Space Kadet SK Leggings",
    },
    {
      _id: "6",
      name: "Space Kadet Tee Shirt",
      category: "Men's Shirts",
      image: "../images/mensblacktee.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 33,
      rating: 4.5,
      numReviews: 10,
      description: "Black Space Kadet Tee Shirt",
    },
    {
      _id: "7",
      name: "Magic Baby Tee",
      category: "Women's Tops",
      image: "../images/magicbabytee.jpg",
      price: 25,
      brand: "Space Kadet",
      countInStock: 3,
      rating: 4.0,
      numReviews: 10,
      description: "Space Kadet Magic Women's Baby Tee",
    },
  ],
};
export default data;
